# Deployment Manifest - Staging Environment
# Auto-promoted from dev environment by CD pipeline
# DO NOT manually edit - CD will overwrite changes
# Last updated: 2026-01-08T17:02:29Z

version: "dev-8e5d356"
ecr_registry: "654654526828.dkr.ecr.eu-central-1.amazonaws.com/chatapp"
ecr_repo: "chatapp"
backend_image: "654654526828.dkr.ecr.eu-central-1.amazonaws.com/chatapp:backend-dev-8e5d356"
frontend_image: "654654526828.dkr.ecr.eu-central-1.amazonaws.com/chatapp:frontend-dev-8e5d356"
deployed_at: "2026-01-08T17:02:29Z"
deployed_by: "jenkins-cd"
git_commit: "b00f0714ae8d3b0aece0c167b218717d86fe5c22"
git_branch: "staging"
promoted_from: "dev"
promoted_at: "2026-01-08T17:02:29Z"
