name: Create Hotfix Branch Workflow

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      app:
        required: true
        type: string

permissions:
  id-token: write
  contents: write
  actions: read

env:
  prefix: "app/${{inputs.app}}/v"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  job:
    name: Create new hotfix
    runs-on: ubuntu-latest
    steps:
      - name: Check for main branch
        run: |
          if [ "${{ github.ref_name }}" != "main" ]; then
            echo "ðŸš« This workflow can only be run on the 'main' branch. Current: ${{ github.ref_name }}"
            exit 1
          fi
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show who triggered the pipeline
        run: |
          echo "ðŸ“£ This release was triggered by: ${{ inputs.name }}"

      - name: Generate new tag (dry run)
        uses: mathieudutour/github-tag-action@v6.1
        id: get_new_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          fetch_all_tags: true
          tag_prefix: ${{env.prefix}}
          default_bump: patch
          release_branches: .*
          
      - name: Show existing tags
        run: git tag --sort=-creatordate | head -n 10

      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.4.0
        with:
          branch: "hotfix/${{steps.get_new_version.outputs.new_tag}}"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: "hotfix/${{steps.get_new_version.outputs.new_tag}}"

      - name: Generate new tag 
        uses: mathieudutour/github-tag-action@v1.0
        id: create_new_tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: "${{steps.get_new_version.outputs.new_version}}-hfc01"
          tag_prefix: ${{env.prefix}}
          release_branches: .*
